[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/run/supervisord.pid
childlogdir=/run
minfds=65536

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[include]
files=/run/mytonctrl-supervisor/*.conf
