#!/usr/bin/python3
"""The subset of systemctl used by MyTonCtrl, backed by supervisord.

Unit files and enable markers are persistent; supervisor's generated files are
runtime state. Reloading units never interrupts an already running service.
"""

import contextlib
import fcntl
import http.client
import json
import os
from pathlib import Path
import re
import shlex
import socket
import sys
import xmlrpc.client


SERVICE_ENVIRONMENT = (
    "MYTONCTRL_SERVICE_UNIT_DIR", "MYTONCTRL_SERVICE_ENABLED_DIR",
    "MYTONCTRL_SUPERVISOR_CONFIG_DIR", "MYTONCTRL_SUPERVISOR_SOCKET",
    "MYTONCTRL_SERVICE_RUNNER",
)


class UnixConnection(http.client.HTTPConnection):
    def __init__(self, socket_path):
        super().__init__("localhost", timeout=90)
        self.socket_path = socket_path

    def connect(self):
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.sock.settimeout(self.timeout)
        self.sock.connect(self.socket_path)


class UnixTransport(xmlrpc.client.Transport):
    def __init__(self, socket_path):
        super().__init__()
        self.socket_path = socket_path

    def make_connection(self, host):
        return UnixConnection(self.socket_path)


def service_name(value):
    name = value[:-8] if value.endswith(".service") else value
    if not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_.@-]*", name):
        raise ValueError(f"Invalid service name: {value}")
    return name


def parse_command(value):
    ignore_failure = value.startswith("-")
    command = shlex.split(value[1:] if ignore_failure else value)
    if not command or not os.path.isabs(command[0]):
        raise ValueError("Service commands must start with an absolute executable path")
    return {"argv": command, "ignore_failure": ignore_failure}


def read_unit(path):
    """Read the simple units generated by the installer without executing text."""
    values = {}
    section = None
    logical_lines = []
    pending = ""
    for line in Path(path).read_text().splitlines():
        line = pending + line.strip()
        if line.endswith("\\"):
            pending = line[:-1] + " "
            continue
        logical_lines.append(line)
        pending = ""
    if pending:
        raise ValueError(f"Unterminated continuation in {path}")
    for line in logical_lines:
        if not line or line.startswith(("#", ";")):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
        elif section == "Service" and "=" in line:
            key, value = (part.strip() for part in line.split("=", 1))
            if not value:
                values[key] = []
            else:
                values.setdefault(key, []).append(value)
    def last(key, default=""):
        return values.get(key, [default])[-1] if values.get(key) else default
    if last("Type", "simple") not in ("simple", "exec"):
        raise ValueError(f"Unsupported service Type in {path}")
    commands = values.get("ExecStart", [])
    if len(commands) != 1:
        raise ValueError(f"Exactly one ExecStart is required in {path}")
    start = parse_command(commands[0])["argv"]
    # Supervisor must own the validator PID, rather than the short-lived
    # parent which the installer's --daemonize argument would create.
    if Path(start[0]).name == "validator-engine" or Path(path).stem == "validator":
        start = [arg for arg in start if arg != "--daemonize"]
    environment = {}
    for value in values.get("Environment", []):
        for assignment in shlex.split(value):
            key, separator, val = assignment.partition("=")
            if not separator or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
                raise ValueError(f"Invalid Environment assignment in {path}")
            environment[key] = val
    restart = last("Restart", "no")
    if restart not in ("no", "always", "on-failure", "on-abnormal", "on-abort"):
        raise ValueError(f"Unsupported Restart policy in {path}")
    return {
        "argv": start,
        "pre": [parse_command(command) for command in values.get("ExecStartPre", [])],
        "user": last("User"),
        "group": last("Group"),
        "directory": last("WorkingDirectory"),
        "environment": environment,
        "restart": restart,
    }


def render_program(name, spec_path, spec, runner):
    command = shlex.join([sys.executable, str(runner), str(spec_path)])
    restart = {"no": "false", "always": "true"}.get(spec["restart"], "unexpected")
    # %% escapes Supervisor interpolation. Commands are parsed into argv by
    # Supervisor and by the runner; neither path invokes a shell.
    command = command.replace("%", "%%")
    return f"""[program:{name}]
command={command}
autostart=false
autorestart={restart}
startsecs=1
startretries=3
stopsignal=TERM
stopwaitsecs=60
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
"""


def process_start_monotonic(pid):
    if not pid:
        return 0
    try:
        # Field 22 is the process start time in clock ticks since boot. The
        # command field can contain spaces or parentheses, so split after it.
        fields = Path(f"/proc/{pid}/stat").read_text().rpartition(")")[2].split()
        return int(fields[19]) * 1_000_000 // os.sysconf("SC_CLK_TCK")
    except (FileNotFoundError, ProcessLookupError):
        return 0


class ServiceManager:
    def __init__(self):
        self.units = Path(os.environ.get("MYTONCTRL_SERVICE_UNIT_DIR", "/etc/systemd/system"))
        self.enabled = Path(os.environ.get("MYTONCTRL_SERVICE_ENABLED_DIR", "/var/ton-work/controller/enabled"))
        self.configs = Path(os.environ.get("MYTONCTRL_SUPERVISOR_CONFIG_DIR", "/run/mytonctrl-supervisor"))
        self.runner = Path(os.environ.get("MYTONCTRL_SERVICE_RUNNER", "/usr/local/lib/mytonctrl/run-service.py"))
        sock = os.environ.get("MYTONCTRL_SUPERVISOR_SOCKET", "/run/supervisor.sock")
        self.rpc = xmlrpc.client.ServerProxy("http://localhost/RPC2", transport=UnixTransport(sock)).supervisor

    @contextlib.contextmanager
    def locked(self):
        self.configs.mkdir(parents=True, exist_ok=True)
        with (self.configs / "systemctl.lock").open("a") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            yield

    def unit_path(self, name):
        return self.units / f"{name}.service"

    def info(self, name):
        try:
            return self.rpc.getProcessInfo(name)
        except xmlrpc.client.Fault as error:
            if error.faultCode == 10:  # BAD_NAME
                return None
            raise

    def reload(self):
        desired = set()
        for unit in sorted(self.units.glob("*.service")):
            if not unit.is_file():
                continue
            name = service_name(unit.name)
            spec = read_unit(unit)
            desired.add(name)
            spec_path = self.configs / f"{name}.json"
            self.write_if_changed(spec_path, json.dumps(spec, sort_keys=True))
            self.write_if_changed(self.configs / f"{name}.conf", render_program(name, spec_path, spec, self.runner))
        for config in self.configs.glob("*.conf"):
            if config.stem not in desired:
                config.unlink()
                (self.configs / f"{config.stem}.json").unlink(missing_ok=True)
        self.rpc.reloadConfig()
        current = {info["group"]: info for info in self.rpc.getAllProcessInfo()}
        for name in sorted(desired - current.keys()):
            self.rpc.addProcessGroup(name)
        # A removed unit may still be running. Keep that process until the
        # user explicitly stops it, just as daemon-reload does with systemd.
        for name in sorted(current.keys() - desired):
            if current[name]["statename"] in ("STOPPED", "EXITED", "FATAL"):
                self.rpc.removeProcessGroup(name)

    @staticmethod
    def write_if_changed(path, contents):
        if path.exists() and path.read_text() == contents:
            return
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(contents)
        temporary.replace(path)

    def start(self, name, restart=False):
        if not self.unit_path(name).is_file():
            raise ValueError(f"Unit {name}.service does not exist")
        self.reload()
        info = self.info(name)
        if info and info["statename"] in ("RUNNING", "STARTING") and not restart:
            return
        if info and info["statename"] in ("RUNNING", "STARTING", "BACKOFF", "STOPPING"):
            self.rpc.stopProcess(name, True)
        # Removing only the target group applies changed unit settings while
        # leaving every other running service alone.
        if self.info(name):
            self.rpc.removeProcessGroup(name)
        self.rpc.addProcessGroup(name)
        self.rpc.startProcess(name, True)

    def stop(self, name):
        info = self.info(name)
        if info and info["statename"] in ("RUNNING", "STARTING", "BACKOFF", "STOPPING"):
            self.rpc.stopProcess(name, True)

    def initialize(self):
        self.reload()
        self.enabled.mkdir(parents=True, exist_ok=True)
        for marker in sorted(self.enabled.glob("*.service")):
            name = service_name(marker.name)
            if self.unit_path(name).is_file():
                self.start(name)


def main(argv=None):
    arguments = list(sys.argv[1:] if argv is None else argv)
    quiet = "--quiet" in arguments or "-q" in arguments
    value_only = "--value" in arguments
    now = "--now" in arguments
    properties = []
    positional = []
    index = 0
    while index < len(arguments):
        argument = arguments[index]
        if argument.startswith("--property="):
            properties.extend(argument.split("=", 1)[1].split(","))
        elif argument in ("--property", "-p"):
            index += 1
            properties.extend(arguments[index].split(","))
        elif argument in ("--quiet", "-q", "--value", "--now", "--no-pager"):
            pass
        elif argument.startswith("-"):
            raise ValueError(f"Unsupported systemctl option: {argument}")
        else:
            positional.append(argument)
        index += 1
    if not positional:
        raise ValueError("A systemctl command is required")
    action, *services = positional
    services = [service_name(name) for name in services]
    manager = ServiceManager()
    if action in ("daemon-reload", "initialize"):
        if services:
            raise ValueError(f"{action} does not accept service names")
        with manager.locked():
            manager.initialize() if action == "initialize" else manager.reload()
        return 0
    if not services:
        raise ValueError(f"{action} requires a service name")
    result = 0
    for name in services:
        if action == "cat":
            print(manager.unit_path(name).read_text(), end="")
        elif action in ("enable", "disable"):
            with manager.locked():
                manager.enabled.mkdir(parents=True, exist_ok=True)
                marker = manager.enabled / f"{name}.service"
                if action == "enable":
                    if not manager.unit_path(name).is_file():
                        raise ValueError(f"Unit {name}.service does not exist")
                    marker.touch()
                else:
                    marker.unlink(missing_ok=True)
                if now:
                    manager.start(name) if action == "enable" else manager.stop(name)
        elif action in ("start", "stop", "restart"):
            with manager.locked():
                manager.stop(name) if action == "stop" else manager.start(name, action == "restart")
        elif action == "is-enabled":
            enabled = (manager.enabled / f"{name}.service").is_file()
            if not quiet:
                print("enabled" if enabled else "disabled")
            result = max(result, 0 if enabled else 1)
        elif action in ("is-active", "status", "show"):
            info = manager.info(name)
            active = bool(info and info["statename"] == "RUNNING")
            if action == "show":
                values = {"MainPID": info["pid"] if info else 0,
                          "ExecMainStartTimestampMonotonic": process_start_monotonic(info["pid"] if info else 0),
                          "ActiveState": "active" if active else "inactive"}
                for prop in properties or values:
                    if prop not in values:
                        raise ValueError(f"Unsupported systemctl property: {prop}")
                    print(values[prop] if value_only else f"{prop}={values[prop]}")
            else:
                if not quiet:
                    if action == "status":
                        print(f"{name}.service: {info['statename'] if info else 'not-found'}")
                    else:
                        print("active" if active else "inactive")
                result = max(result, 0 if active else 3)
        else:
            raise ValueError(f"Unsupported systemctl command: {action}")
    return result


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PermissionError as error:
        if os.geteuid() != 0 and (os.environ.get("MYTONCTRL_CONTAINER") == "1"
                                or Path("/etc/mytonctrl-container").exists()):
            # Normal MyTonCtrl status and telemetry calls are unprivileged.
            # Keep the socket private and use the container's configured sudo
            # rule, including the service paths of a custom TON_WORK_DIR.
            try:
                os.execv("/usr/bin/sudo", [
                    "sudo", "-n", "--preserve-env=" + ",".join(SERVICE_ENVIRONMENT),
                    sys.executable, os.path.abspath(__file__), *sys.argv[1:],
                ])
            except OSError:
                pass
        print(f"systemctl: {error}", file=sys.stderr)
        sys.exit(1)
    except (ValueError, OSError, IndexError, xmlrpc.client.Error) as error:
        print(f"systemctl: {error}", file=sys.stderr)
        sys.exit(1)
